# Generated by Django 3.1.2 on 2020-11-16 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='SolicitudDulces',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=500)),
                ('dulce_dia', models.BooleanField()),
                ('direccion', models.CharField(max_length=150)),
                ('entrega_inmediata', models.BooleanField()),
                ('factura', models.BooleanField()),
            ],
            options={
                'db_table': 'solicitud_dulces',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nick', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipoUsuario', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appdulceria.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdulceria.producto')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdulceria.usuario')),
            ],
            options={
                'db_table': 'item_carrito',
            },
        ),
    ]
